#pragma once

// dinput.h에 정의된 매크로를 기반으로 했음
enum GKEY_DEF : unsigned int
{

GKEY_DEF_ESCAPE          = 0x01,
GKEY_DEF_1               = 0x02,
GKEY_DEF_2               = 0x03,
GKEY_DEF_3               = 0x04,
GKEY_DEF_4               = 0x05,
GKEY_DEF_5               = 0x06,
GKEY_DEF_6               = 0x07,
GKEY_DEF_7               = 0x08,
GKEY_DEF_8               = 0x09,
GKEY_DEF_9               = 0x0A,
GKEY_DEF_0               = 0x0B,
GKEY_DEF_MINUS           = 0x0C,    /* - on main keyboard */
GKEY_DEF_EQUALS          = 0x0D,
GKEY_DEF_BACK            = 0x0E,    /* backspace */
GKEY_DEF_TAB             = 0x0F,
GKEY_DEF_Q               = 0x10,
GKEY_DEF_W               = 0x11,
GKEY_DEF_E               = 0x12,
GKEY_DEF_R               = 0x13,
GKEY_DEF_T               = 0x14,
GKEY_DEF_Y               = 0x15,
GKEY_DEF_U               = 0x16,
GKEY_DEF_I               = 0x17,
GKEY_DEF_O               = 0x18,
GKEY_DEF_P               = 0x19,
GKEY_DEF_LBRACKET        = 0x1A,
GKEY_DEF_RBRACKET        = 0x1B,
GKEY_DEF_RETURN          = 0x1C,    /* Enter on main keyboard */
GKEY_DEF_LCONTROL        = 0x1D,
GKEY_DEF_A               = 0x1E,
GKEY_DEF_S               = 0x1F,
GKEY_DEF_D               = 0x20,
GKEY_DEF_F               = 0x21,
GKEY_DEF_G               = 0x22,
GKEY_DEF_H               = 0x23,
GKEY_DEF_J               = 0x24,
GKEY_DEF_K               = 0x25,
GKEY_DEF_L               = 0x26,
GKEY_DEF_SEMICOLON       = 0x27,
GKEY_DEF_APOSTROPHE      = 0x28,
GKEY_DEF_GRAVE           = 0x29,    /* accent grave */
GKEY_DEF_LSHIFT          = 0x2A,
GKEY_DEF_BACKSLASH       = 0x2B,
GKEY_DEF_Z               = 0x2C,
GKEY_DEF_X               = 0x2D,
GKEY_DEF_C               = 0x2E,
GKEY_DEF_V               = 0x2F,
GKEY_DEF_B               = 0x30,
GKEY_DEF_N               = 0x31,
GKEY_DEF_M               = 0x32,
GKEY_DEF_COMMA           = 0x33,
GKEY_DEF_PERIOD          = 0x34,    /* . on main keyboard */
GKEY_DEF_SLASH           = 0x35,    /* / on main keyboard */
GKEY_DEF_RSHIFT          = 0x36,
GKEY_DEF_MULTIPLY        = 0x37,    /* * on numeric keypad */
GKEY_DEF_LMENU           = 0x38,    /* left Alt */
GKEY_DEF_SPACE           = 0x39,
GKEY_DEF_CAPITAL         = 0x3A,
GKEY_DEF_F1              = 0x3B,
GKEY_DEF_F2              = 0x3C,
GKEY_DEF_F3              = 0x3D,
GKEY_DEF_F4              = 0x3E,
GKEY_DEF_F5              = 0x3F,
GKEY_DEF_F6              = 0x40,
GKEY_DEF_F7              = 0x41,
GKEY_DEF_F8              = 0x42,
GKEY_DEF_F9              = 0x43,
GKEY_DEF_F10             = 0x44,
GKEY_DEF_NUMLOCK         = 0x45,
GKEY_DEF_SCROLL          = 0x46,    /* Scroll Lock */
GKEY_DEF_NUMPAD7         = 0x47,
GKEY_DEF_NUMPAD8         = 0x48,
GKEY_DEF_NUMPAD9         = 0x49,
GKEY_DEF_SUBTRACT        = 0x4A,    /* - on numeric keypad */
GKEY_DEF_NUMPAD4         = 0x4B,
GKEY_DEF_NUMPAD5         = 0x4C,
GKEY_DEF_NUMPAD6         = 0x4D,
GKEY_DEF_ADD             = 0x4E,    /* + on numeric keypad */
GKEY_DEF_NUMPAD1         = 0x4F,
GKEY_DEF_NUMPAD2         = 0x50,
GKEY_DEF_NUMPAD3         = 0x51,
GKEY_DEF_NUMPAD0         = 0x52,
GKEY_DEF_DECIMAL         = 0x53,    /* . on numeric keypad */
GKEY_DEF_OEM_102         = 0x56,    /* <> or \| on RT 102-key keyboard (Non-U.S.) */
GKEY_DEF_F11             = 0x57,
GKEY_DEF_F12             = 0x58,
GKEY_DEF_F13             = 0x64,    /*                     (NEC PC98) */
GKEY_DEF_F14             = 0x65,    /*                     (NEC PC98) */
GKEY_DEF_F15             = 0x66,    /*                     (NEC PC98) */
GKEY_DEF_KANA            = 0x70,    /* (Japanese keyboard)            */
GKEY_DEF_ABNT_C1         = 0x73,    /* /? on Brazilian keyboard */
GKEY_DEF_CONVERT         = 0x79,    /* (Japanese keyboard)            */
GKEY_DEF_NOCONVERT       = 0x7B,    /* (Japanese keyboard)            */
GKEY_DEF_YEN             = 0x7D,    /* (Japanese keyboard)            */
GKEY_DEF_ABNT_C2         = 0x7E,    /* Numpad . on Brazilian keyboard */
GKEY_DEF_NUMPADEQUALS    = 0x8D,    /* = on numeric keypad (NEC PC98) */
GKEY_DEF_PREVTRACK       = 0x90,    /* Previous Track (DIK_CIRCUMFLEX on Japanese keyboard) */
GKEY_DEF_AT              = 0x91,    /*                     (NEC PC98) */
GKEY_DEF_COLON           = 0x92,    /*                     (NEC PC98) */
GKEY_DEF_UNDERLINE       = 0x93,    /*                     (NEC PC98) */
GKEY_DEF_KANJI           = 0x94,    /* (Japanese keyboard)            */
GKEY_DEF_STOP            = 0x95,    /*                     (NEC PC98) */
GKEY_DEF_AX              = 0x96,    /*                     (Japan AX) */
GKEY_DEF_UNLABELED       = 0x97,    /*                        (J3100) */
GKEY_DEF_NEXTTRACK       = 0x99,    /* Next Track */
GKEY_DEF_NUMPADENTER     = 0x9C,    /* Enter on numeric keypad */
GKEY_DEF_RCONTROL        = 0x9D,
GKEY_DEF_MUTE            = 0xA0,    /* Mute */
GKEY_DEF_CALCULATOR      = 0xA1,    /* Calculator */
GKEY_DEF_PLAYPAUSE       = 0xA2,    /* Play / Pause */
GKEY_DEF_MEDIASTOP       = 0xA4,    /* Media Stop */
GKEY_DEF_VOLUMEDOWN      = 0xAE,    /* Volume - */
GKEY_DEF_VOLUMEUP        = 0xB0,    /* Volume + */
GKEY_DEF_WEBHOME         = 0xB2,    /* Web home */
GKEY_DEF_NUMPADCOMMA     = 0xB3,    /* , on numeric keypad (NEC PC98) */
GKEY_DEF_DIVIDE          = 0xB5,    /* / on numeric keypad */
GKEY_DEF_SYSRQ           = 0xB7,
GKEY_DEF_RMENU           = 0xB8,    /* right Alt */
GKEY_DEF_PAUSE           = 0xC5,    /* Pause */
GKEY_DEF_HOME            = 0xC7,    /* Home on arrow keypad */
GKEY_DEF_UP              = 0xC8,    /* UpArrow on arrow keypad */
GKEY_DEF_PRIOR           = 0xC9,    /* PgUp on arrow keypad */
GKEY_DEF_LEFT            = 0xCB,    /* LeftArrow on arrow keypad */
GKEY_DEF_RIGHT           = 0xCD,    /* RightArrow on arrow keypad */
GKEY_DEF_END             = 0xCF,    /* End on arrow keypad */
GKEY_DEF_DOWN            = 0xD0,    /* DownArrow on arrow keypad */
GKEY_DEF_NEXT            = 0xD1,    /* PgDn on arrow keypad */
GKEY_DEF_INSERT          = 0xD2,    /* Insert on arrow keypad */
GKEY_DEF_DELETE          = 0xD3,    /* Delete on arrow keypad */
GKEY_DEF_LWIN            = 0xDB,    /* Left Windows key */
GKEY_DEF_RWIN            = 0xDC,    /* Right Windows key */
GKEY_DEF_APPS            = 0xDD,    /* AppMenu key */
GKEY_DEF_POWER           = 0xDE,    /* System Power */
GKEY_DEF_SLEEP           = 0xDF,    /* System Sleep */
GKEY_DEF_WAKE            = 0xE3,    /* System Wake */
GKEY_DEF_WEBSEARCH       = 0xE5,    /* Web Search */
GKEY_DEF_WEBFAVORITES    = 0xE6,    /* Web Favorites */
GKEY_DEF_WEBREFRESH      = 0xE7,    /* Web Refresh */
GKEY_DEF_WEBSTOP         = 0xE8,    /* Web Stop */
GKEY_DEF_WEBFORWARD      = 0xE9,    /* Web Forward */
GKEY_DEF_WEBBACK         = 0xEA,    /* Web Back */
GKEY_DEF_MYCOMPUTER      = 0xEB,    /* My Computer */
GKEY_DEF_MAIL            = 0xEC,    /* Mail */
GKEY_DEF_MEDIASELECT     = 0xED,    /* Media Select */

};
