#pragma once

enum GMOUSE_BUTTONS : unsigned int
{
	MOUSE_BUTTONS_LEFT   = 0x00,
	MOUSE_BUTTONS_RIGHT  = 0x01,
	MOUSE_BUTTONS_MIDDLE = 0x02,
	MOUSE_BUTTONS_X1     = 0x03,
	MOUSE_BUTTONS_X2     = 0x04,
	MOUSE_BUTTONS_X3     = 0x05,
	MOUSE_BUTTONS_X4     = 0x06,
	MOUSE_BUTTONS_X5     = 0x07,
};